# Generated by Django 3.2.8 on 2024-11-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fono',
        ),
        migrations.AddField(
            model_name='employee',
            name='telefono',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
